name: StarBook
description: Collection of useful Commands
author: StarTux
version: 0.1
main: com.winthier.starbook.StarBookPlugin
depend: []
commands:
  test:
    permission: starbook.test
    usage: '/test'
  slap:
    permission: starbook.slap
    usage: '/slap [-vhs] <player>'
  rocket:
    permission: starbook.rocket
    usage: '/rocket [-hs] <player>'
  sound:
    permission: starbook.sound
    usage: '/sound <soundname>'
  spawnmob:
    permission: starbook.spawnmob
    usage: '/spawnmob <mob> [amount]'
  playertime:
    permission: starbook.playertime
    usage: '/playertime reset|<time>'
  time:
    permission: starbook.time
    usage: '/time [time]'
  moon:
    permission: starbook.moon
    usage: '/moon'
  cropcliff:
    permission: starbook.cropcliff
permissions: {}
