name: StarBook
description: Collection of useful Commands
author: StarTux
version: 0.1
api-version: 1.13
website: http://cavetale.com
main: com.winthier.starbook.StarBookPlugin
depend: [Core, GenericEvents]
softdepend: [WorldEdit, Connect]
commands:
  slap:
    permission: starbook.slap
    usage: '/slap [-vhs] <player>'
  rocket:
    permission: starbook.rocket
    usage: '/rocket [-hs] <player>'
  sound:
    permission: starbook.sound
    description: Play sound effects in your ears
    usage: '/sound <soundname> [volume] [pitch] [target]'
  particles:
    permission: starbook.particles
    description: Show particles in front of your face
    usage: '/particles <particle> [count] [offset] [extra] [data]'
  spawnmob:
    permission: starbook.spawnmob
    usage: '/spawnmob <mob> [amount]'
  playertime:
    permission: starbook.playertime
    description: Change the time for your client
    usage: '/playertime reset|<time>'
  who:
    aliases: [ list, ls, online ]
    permission: starbook.who
    description: List players on all servers
    usage: '/who'
  time:
    permission: starbook.time
    usage: '/time [time]'
  moon:
    permission: starbook.moon
    usage: '/moon'
  cropcliff:
    permission: starbook.cropcliff
  opme:
    permission: starbook.opme
    usage: '/opme'
  near:
    permission: starbook.near
    usage: '/near'
  script:
    permission: starbook.script
    usage: '/script'
  worldedithighlight:
    aliases: [ wehl ]
    permission: starbook.wehl
    usage: '/wehl'
  getblock:
    permission: starbook.getblock
    usage: '/getblock'
  plugininfo:
    permission: starbook.plugininfo
    aliases: [ pluginfo ]
    usage: |-
      /plugininfo list
      /plugininfo dump <plugin>
      /plugininfo depend <plugin>
      /plugininfo database
      /plugininfo author <name>
      /plugininfo nauthor <name>
      /plugininfo listen <event>
      /plugininfo permission <permission>
      /plugininfo command <cmd>
  poof:
    permission: starbook.poof
    aliases: [ vanish ]
    usage: /poof - vanish/reappear
  heal:
    permission: starbook.heal
    usage: /heal <player> - Fill health bar
  feed:
    permission: starbook.feed
    usage: /feed <player> - Fill hunger bar
  starve:
    permission: starbook.starve
    usage: /starve <player> - Empty hunger bar
  wand:
    permission: starbook.wand
  sel:
    permission: starbook.wand
  sel1:
    permission: starbook.wand
  sel2:
    permission: starbook.wand
  reloaddata:
    description: Reload data packs
    permission: starbook.reloaddata
  findsign:
    description: Find a sign
    permission: starbook.findsign
    usage: /findsigh <text> - Locate signs containing text
  signedit:
    description: Edit signs
    permission: starbook.signedit
    aliases: [signed]
    usage: |-
      /signedit - Open the sign
      /signedit <#line> <text> - Edit line number
permissions:
  onlinelist.staff:
    default: op
    description: Be highlighted as staff on the online list

  starbook.slap:
    default: op
    description: Use /slap

  starbook.rocket:
    default: op
    description: Use /rocket

  starbook.particles:
    default: op
    description: Use /particles

  starbook.spawnmob:
    default: op
    description: Use /spawnmob

  starbook.playertime:
    default: op
    description: Use /playertime

  starbook.who:
    default: op
    description: Use /who, /list, /online

  starbook.time:
    default: op
    description: Use /time

  starbook.poof:
    default: op
    description: Use /poof

  starbook.heal:
    default: op
    description: Use /heal

  starbook.feed:
    default: op
    description: Use /feed

  starbook.starve:
    default: op
    description: Use /starve

  starbook.reloaddata:
    default: op
    description: Use /reloaddata

  starbook.findsign:
    default: op
    description: Use /findsign

  starbook.signedit:
    default: op
    description: Use /signedit

  starbook.signedit.color:
    default: op
    description: Use color codes in sign edits

  starbook.signedit.emoji:
    default: op
    description: Use emoji in sign edits

  starbook.signedit.emoji.hidden:
    default: op
    description: Use hidden emoji on signs
