main: com.winthier.starbook.StarBookPlugin
name: StarBook

version: 0.1
api-version: 1.19

description: Collection of useful Commands
author: StarTux
website: http://cavetale.com

depend: [Core]
softdepend: [WorldMarker]

commands:

  slap:
    permission: starbook.slap
    usage: '/slap [-vhs] <player>'

  rocket:
    permission: starbook.rocket
    usage: '/rocket [-hs] <player>'

  sound:
    permission: starbook.sound
    description: Play sound effects in your ears
    usage: '/sound <soundname> [volume] [pitch] [target]'

  particles:
    permission: starbook.particles
    description: Show particles in front of your face
    usage: '/particles <particle> [count] [offset] [extra] [data]'

  spawnmob:
    permission: starbook.spawnmob
    usage: '/spawnmob <mob> [amount]'

  playertime:
    permission: starbook.playertime
    description: Change the time for your client
    usage: '/playertime reset|<time>'

  time:
    permission: starbook.time
    usage: '/time [time]'

  moon:
    permission: starbook.moon
    usage: '/moon'

  opme:
    permission: starbook.opme
    usage: '/opme'

  near:
    permission: starbook.near
    usage: '/near'

  script:
    permission: starbook.script
    usage: '/script'

  worldedithighlight:
    aliases: [ wehl ]
    permission: starbook.wehl
    usage: '/wehl'

  getblock:
    permission: starbook.getblock
    usage: '/getblock'

  poof:
    permission: starbook.poof
    aliases: [ vanish ]
    usage: /poof - vanish/reappear

  heal:
    permission: starbook.heal
    usage: /heal <player> - Fill health bar

  feed:
    permission: starbook.feed
    usage: /feed <player> - Fill hunger bar

  starve:
    permission: starbook.starve
    usage: /starve <player> - Empty hunger bar

  reloaddata:
    description: Reload data packs
    permission: starbook.reloaddata

  findsign:
    description: Find a sign
    permission: starbook.findsign
    usage: /findsign <text> - Locate signs containing text

  findchest:
    description: Find a chest
    permission: starbook.findchest
    usage: /findchest <text> - Locate chests containing text

  signedit:
    description: Edit signs
    permission: starbook.signedit
    aliases: [signed]
    usage: |-
      /signedit - Open the sign
      /signedit <#line> <text> - Edit line number

  getping:
    description: Get your ping
    permission: starbook.getping
    aliases: []
    usage: /getping

  makebook:
    description: Put text in book
    permission: starbook.makebook
    aliases: []
    usage: /makebook <text>

  markblocks:
    description: Mark selection with WorldMarker
    permission: starbook.markblocks
    aliases: []
    usage: |-
      "/markblocks <id>" Set id
      "/markblocks -" Reset ids

  changebiome:
    aliases: []
    description: Change biome in WE selection
    permission: starbook.changebiome
    usage: /changebiome <biome>

  changeblocks:
    aliases: []
    description: Change blocks in WE selection
    permission: starbook.changeblocks
    usage: /changeblocks <block>

  clearcontainers:
    aliases: []
    description: Clear selected containers
    permission: starbook.clearcontainers
    usage: /clearcontainers

  setendgateway:
    aliases: []
    permission: starbook.setendgateway
    description: Create an end gateway which never beams in your WE selection
    usage: /setendgateway

  transferaccount:
    aliases: []
    permission: starbook.transferaccount
    description: Transfer accounts
    usage: /transferaccount <from> <to>

  gmc:
    aliases: []
    permission: minecraft.command.gamemode
    description: Set game mode to creative
    usage: /gmc

  gmp:
    aliases: []
    permission: minecraft.command.gamemode
    description: Set game mode to spectator
    usage: /gmp

  gms:
    aliases: []
    permission: minecraft.command.gamemode
    description: Set game mode to survival
    usage: /gms

  gma:
    aliases: []
    permission: minecraft.command.gamemode
    description: Set game mode to adventure
    usage: /gma

  tpp:
    permission: starbook.tpp
    description: Teleport to player
    usage: /tpp <player>

  dumpheap:
    permission: starbook.dumpheap
    description: Dump the heap
    usage: /dumpheap <live>

  restoreitems:
    permission: starbook.restoreitems
    description: Restore items
    usage: /restoreitems <code>

  viewdistance:
    permission: starbook.viewdistance
    description: Set player view distance
    usage: /viewdistance <value>

  recorder:
    permission: starbook.recorder
    description: Record note blocks
    usage: /recorder

  makemodel:
    permission: starbook.makemodel
    description: Make a resource pack model
    usage: /makemodel

  craft:
    permission: starbook.craft
    description: Open crafting bench
    usage: /craft

permissions:
  onlinelist.staff:
    default: op
    description: Be highlighted as staff on the online list

  starbook.slap:
    default: op
    description: Use /slap

  starbook.rocket:
    default: op
    description: Use /rocket

  starbook.particles:
    default: op
    description: Use /particles

  starbook.spawnmob:
    default: op
    description: Use /spawnmob

  starbook.playertime:
    default: op
    description: Use /playertime

  starbook.time:
    default: op
    description: Use /time

  starbook.poof:
    default: op
    description: Use /poof

  starbook.heal:
    default: op
    description: Use /heal

  starbook.feed:
    default: op
    description: Use /feed

  starbook.starve:
    default: op
    description: Use /starve

  starbook.reloaddata:
    default: op
    description: Use /reloaddata

  starbook.findsign:
    default: op
    description: Use /findsign

  starbook.findchest:
    default: op
    description: Use /findchest

  starbook.signedit:
    default: op
    description: Use /signedit

  starbook.signedit.color:
    default: op
    description: Use color codes in sign edits

  starbook.signedit.color.decorate:
    default: op
    description: Use text decorations in sign edits

  starbook.signedit.color.obfuscate:
    default: op
    description: Use color codes in sign edits

  starbook.signedit.emoji:
    default: op
    description: Use emoji in sign edits

  starbook.signedit.emoji.hidden:
    default: op
    description: Use hidden emoji on signs

  starbook.getping:
    default: op
    description: Use /getping

  starbook.getping.other:
    default: op
    description: Use /getping

  starbook.book:
    default: op
    description: Use /book

  starbook.markblocks:
    default: op
    description: Use /markblocks

  starbook.changebiome:
    default: op
    description: Use /changebiome

  starbook.changeblocks:
    default: op
    description: Use /changeblocks

  starbook.setendgateway:
    default: op
    description: Use /setendgateway

  starbook.transferaccount:
    default: op
    description: Use /transferaccount

  starbook.tpp:
    default: op
    description: Use /tpp

  starbook.dumpheap:
    default: op
    description: Use /dumpheap

  starbook.restoreitems:
    default: op
    description: Use /restoreitems

  starbook.viewdistance:
    default: op
    description: Use /viewdistance

  starbook.recorder:
    default: op
    description: Use /recorder

  starbook.makemodel:
    default: op
    description: Use /makemodel

  starbook.craft:
    default: op
    descriptioN: Use /craft