name: StarBook
description: Collection of useful Commands
author: StarTux
version: 0.1
main: com.winthier.starbook.StarBookPlugin
depend: []
softdepend: [WorldEdit]
commands:
  test:
    permission: starbook.test
    usage: '/test'
  slap:
    permission: starbook.slap
    usage: '/slap [-vhs] <player>'
  rocket:
    permission: starbook.rocket
    usage: '/rocket [-hs] <player>'
  sound:
    permission: starbook.sound
    usage: '/sound <soundname> [volume] [pitch] [target]'
  spawnmob:
    permission: starbook.spawnmob
    usage: '/spawnmob <mob> [amount]'
  playertime:
    permission: starbook.playertime
    usage: '/playertime reset|<time>'
  time:
    permission: starbook.time
    usage: '/time [time]'
  moon:
    permission: starbook.moon
    usage: '/moon'
  cropcliff:
    permission: starbook.cropcliff
  opme:
    permission: starbook.opme
    usage: '/opme'
  near:
    permission: starbook.near
    usage: '/near'
  script:
    permission: starbook.script
    usage: '/script'
  worldedithighlight:
    aliases: [ wehl ]
    permission: starbook.wehl
    usage: '/wehl'
  getblock:
    permission: starbook.getblock
    usage: '/getblock'
  plugininfo:
    permission: starbook.plugininfo
    aliases: [ pluginfo ]
    usage: |-
      /plugininfo list
      /plugininfo depends <plugin>
      /plugininfo database
      /plugininfo author <name>
  poof:
    permission: starbook.poof
    aliases: [ vanish ]
    usage: /poof - vanish/reappear
permissions: {}
